Libros/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('LibrosApp/', include('LibrosApp.urls')),
]

#Urls para las imagenes

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

LibrosApp/urls.py
from django import views
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("inicio/", inicio, name = "inicio"),
    path("buscar/", buscarLibros, name = "buscar"),
    path("resultados/", buscar, name = "Resultado"),
    path("login/", loginUsuario, name = "login"),
    path("register/", register, name = "register"),
    path("logout", LogoutView.as_view(template_name="LibrosApp/inicio.html"), name = "salir"),
    path("editarUsuario/", editarUsuario, name = "editUser"),
    path("agregarAvatar/", agregarAvatar, name="agregarAvatar"),
    path("perfil/", perfil, name = "perfill"),
    path('detallelibro/<int:pk>/', detalleLibro.as_view(), name='detallelibro'),
    
    #CRUD
    path("libros/", posts, name = "libros"),
    path("librosposts/", postear, name = "librosposts"),
    path("editarlibro/<Posteo>", editarPost, name = "editarlibro"),
    path("eliminarlibro/<Posteo>", eliminarPost, name = "eliminarlibro"),
]

LibrosApp/models.py
from email.policy import default
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User

class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="avatares", default='', null=True, blank=True)

    class Meta:
        verbose_name = "Avatar"
        verbose_name_plural = "Avatares"

class Perfil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    imagen = models.ImageField(default='', null=True, blank=True)

    def __str__(self):
        return f'Perfil de {self.user.username}'

class Libros(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    imagen = models.ImageField(upload_to="publicaciones", null=True, blank=True)
    fecha_creacion = models.DateTimeField(default=timezone.now)
    nombreLibro = models.CharField(max_length=60,null=True, blank=True)
    autor = models.CharField(max_length=60,null=True, blank=True)
    capitulos = models.IntegerField()
    genero = models.CharField(max_length=60,null=True, blank=True)
    anio = models.IntegerField(null=True, blank=True)
    descripcion = models.TextField(null=True, blank=True)
    class Meta:
        ordering = ["-fecha_creacion"]
        verbose_name = "libros"
        verbose_name_plural = "libross"
    def __str__(self):
        return f'{self.user.username}: {self.nombreLibro}: {self.genero}'

LibrosApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Avatar, Libros

class RegistroForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={"class":"eform","placeholder":"Ingrese un correo"}), label="")
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"class":"eform","placeholder":"Ingrese una contraseña"}), label="")
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"class":"eform","placeholder":"Repita la contraseña"}), label="")
    class Meta:
        model = User
        fields = ["username","email","password1","password2"]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = ""
        self.fields["username"].widget.attrs.update({"class":"eform","placeholder":"Nombre"})
        self.fields["username"].help_text = None

class EditarUsuarioForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={"class":"eform","placeholder":"Ingrese un correo"}), label="")
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"class":"eform","placeholder":"Ingrese una contraseña"}), label="")
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"class":"eform","placeholder":"Repita la contraseña"}), label="")
    class Meta:
        model = User
        fields = ["username","email","password1","password2"]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = ""
        self.fields['username'].widget = forms.widgets.TextInput(attrs={"class":"eform",'placeholder': 'Nombre'})
        self.fields['username'].help_text = None

class AvatarFormulario(forms.ModelForm):
    class Meta:
        model = Avatar
        fields = ['imagen']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["imagen"].label = ""
        self.fields["imagen"].help_text = None

class MyAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = ""
        self.fields['username'].widget = forms.widgets.TextInput(attrs={"class":"eform",'placeholder': 'Nombre'})
        self.fields["password"].label = ""
        self.fields['password'].widget = forms.widgets.PasswordInput(attrs={"class":"eform",'placeholder': 'Contraseña'})

class LibrosForm(forms.ModelForm):
    nombreLibro = forms.CharField(widget=forms.TextInput(attrs={"class":"eform","placeholder":"Título"}), label="")
    genero = forms.CharField(widget=forms.TextInput(attrs={"class":"eform","placeholder":"Genero"}), label="")
    anio = forms.CharField(widget=forms.TextInput(attrs={"class":"eform","placeholder":"Año de creacion"}), label="")
    autor = forms.CharField(widget=forms.TextInput(attrs={"class":"eform","placeholder":"Autor"}), label="")
    capitulos = forms.IntegerField(widget=forms.NumberInput(attrs={"class":"eform","placeholder":"Capitulos"}), label="")
    descripcion = forms.CharField(label="", widget=forms.Textarea(attrs={"rows":2, "class":"eform","placeholder":"Escribe aquí una descripción o escritura"}), required=True)
    imagen = forms.URLField(widget=forms.URLInput(attrs={"class":"eform","placeholder":"URL de tu imagen"}), label="")

    class Meta:
        model = Libros
        fields = ["nombreLibro", "autor","genero", "capitulos", "anio", "descripcion", "imagen"]

LibrosApp/views.py
#from typing_extensions import Self
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import *
from .forms import *
from django.contrib.auth import login, authenticate
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib import messages

def inicio(request):
    return render(request, "LibrosApp/inicio.html")

@login_required
def buscarLibros(request):
    return render(request, "LibrosApp/buscar.html")

@login_required
def buscar(request):
    if request.GET["titulo"]:
        buscar = request.GET["titulo"]
        libros = Libros.objects.filter(nombreLibro__icontains=buscar)
        return render(request, "LibrosApp/resultados.html", {"libros":libros, "buscar":buscar})
    else:
        mensaje = "No enviaste datos."
    return HttpResponse(mensaje)

def loginUsuario(request):
    if request.method == "POST":
        ingresar = MyAuthenticationForm(request, data = request.POST)
        if ingresar.is_valid():
            usuario = ingresar.cleaned_data.get("username")
            contra = ingresar.cleaned_data.get("password")
            user = authenticate(username = usuario, password = contra)
            if user:
                login(request, user)
                return render(request, "LibrosApp/inicio.html",{"mensaje":f"hola {user}"})
        else:
            return render(request, "LibrosApp/inicio.html",{"mensaje":f"Datos incorrectos"})
    else:
        ingresar = MyAuthenticationForm()
    return render(request, "LibrosApp/login.html",{"ingresar":ingresar})

def register(request):
    if request.method == "POST":
        registrar = RegistroForm(request.POST)
        if registrar.is_valid():
            nombreUsuario = registrar.cleaned_data["username"]
            registrar.save()
            messages.success(request, f'Usuario {nombreUsuario} creado')
            return render(request, "LibrosApp/inicio.html",{"mensaje":f"Usuario {nombreUsuario} creado!!"})
    else:
        registrar = RegistroForm()
    return render(request, "LibrosApp/registro.html",{"registrar":registrar})

@login_required
def editarUsuario(request):
    userConect = request.user
    if request.method == "POST":
        usuarioForm = EditarUsuarioForm(request.POST)
        if usuarioForm.is_valid():
            info = usuarioForm.cleaned_data
            userConect.username = info["username"]
            userConect.email = info["email"]
            userConect.password1 = info["password1"]
            userConect.password2 = info["password2"]
            userConect.save()
            return render(request, "LibrosApp/inicio.html")
    else:
        usuarioForm = EditarUsuarioForm(initial={"email": userConect.email})
    return render(request, "LibrosApp/editarusuario.html", {"userEdit":usuarioForm, "userOn":userConect})

@login_required
def agregarAvatar(request):
    if request.method == "POST":
        avatarForm = AvatarFormulario(request.POST, request.FILES)
        if avatarForm.is_valid():
            info = avatarForm.cleaned_data
            avatar = Avatar(user=request.user, imagen=info['imagen'])
            avatar.save()
            return render(request, "LibrosApp/perfil.html")
    else:
        avatarForm = AvatarFormulario()
    return render(request, "LibrosApp/avatar.html",{'avatarForm':avatarForm})

@login_required
def perfil(request):
    return render(request, "LibrosApp/perfil.html")

@login_required
def posts(request):
    posts = Libros.objects.all()
    context = {"posts":posts}
    return render(request, "LibrosApp/libros.html", context)

@login_required
def postear(request):
    current_user = get_object_or_404(User, pk=request.user.pk)
    if request.method == "POST":
        posteo = LibrosForm(request.POST, request.FILES)
        if posteo.is_valid():
            post = posteo.save(commit=False)
            post.user = current_user
            posteo.save()
            messages.success(request, "Publicación enviado con éxito")
            return render(request, "LibrosApp/padre.html")
    else:
        posteo = LibrosForm()
    return render(request,"LibrosApp/formulario.html",{"posteo":posteo})

@login_required
def editarPost(request, Posteo):
    editar = Libros.objects.get(nombreLibro = Posteo)
    if request.method == "POST":
        postEditar = LibrosForm(request.POST, request.FILES)
        if postEditar.is_valid():
            info = postEditar.cleaned_data
            editar.imagen = info["imagen"]
            editar.nombreLibro = info["nombreLibro"]
            editar.genero = info["genero"]
            editar.anio = info["anio"]
            editar.descripcion = info["descripcion"]
            editar.save()
            messages.success(request, "Publicación editada con éxito")
            return render(request, "LibrosApp/libros.html")
    else:
        postEditar = LibrosForm(initial={"imagen": editar.imagen, "nombreLibro": editar.nombreLibro, "genero": editar.genero, "anio": editar.anio, "descripcion": editar.descripcion})
    return render(request, "LibrosApp/editarlibros.html", {"editar":postEditar, "nombre":Posteo})

@login_required
def eliminarPost(request, Posteo):
    eliminar = Libros.objects.get(nombreLibro = Posteo)
    eliminar.delete()
    nombreLibros = Libros.objects.all()
    contexto = {"nombreLibros":nombreLibros}
    return render(request, "LibrosApp/inicio.html", contexto)

class detalleLibro(LoginRequiredMixin, DetailView):
    model = Libros
    context_object_name = 'verlibro'
    template_name = 'LibrosApp/detallelibro.html'

LibrosApp/templates/LibroApp/avatar.html
{% extends 'libroApp/padre.html' %}

{%load static%}

{% block contenido1 %}

<div class="c3">
    <form action="" enctype="multipart/form-data" method="POST"> {% csrf_token %}
        <table align="center">
            {{avatarForm.as_table}}
        </table>
        <input type="submit" value="Subir imagen" class="botonform">
    </form>
</div>

{% endblock %}

LibrosApp/templates/LibroApp/buscar.html
{% extends 'libroApp/padre.html' %}

{%load static%}

{% block contenido1 %}

<section>
    <form action="/LibrosApp/resultados/" method="GET">
        <input type="text" name="nombreLibro" id="nombreLibro" placeholder="Título">
        <input type="submit" value="Buscar">
    </form>
</section>


{% endblock %}

LibrosApp/templates/LibroApp/editarlibros.html
{% extends 'libroApp/padre.html' %}

{%load static%}

{% block contenido1 %}

<form action="" enctype="multipart/form-data" method="POST"> {% csrf_token %}
    <table margin="center">
        {{editar.as_table}}
    </table>
    <input type="submit" value="Confirmar" class="botonform">
</form>

{% endblock %}

LibrosApp/templates/LibroApp/eliminarlibro.html
{% extends 'libroApp/padre.html' %}

{%load static%}

{% block contenido1 %}



{% endblock %}

LibrosApp/templates/LibroApp/formulario.html
{% extends 'libroApp/padre.html' %}

{%load static%}

{% block contenido1 %}


<form action="" enctype="multipart/form-data" method="POST"> {% csrf_token %}
    <table style="align-content: center;">
        {{postear.as_table}}
    </table>
    <input type="submit" value="aceptar" class="botonform">
</form>



{% endblock %}

LibrosApp/templates/LibroApp/inicio.html
{% extends 'LibroApp/padre.html' %}
       {% block contenido1 %}
        <!-- About-->
        <section class="content-section bg-light" id="about">
            <div class="container px-4 px-lg-5 text-center">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-10">
                        <h2>¿QUÉ ES MUNDO LIBRO?</h2>
                        <p class="lead mb-5">
                            Somos una tienda digital que cumplimos todas sus necesidades como lectores,
                            otorgamos libros en formato PDF y también les damos la opción de comprar
                            su libro favorito y nosotros lo envíamos a cualquier agencia de mensajería.
                            <a href="https://unsplash.com/">Unsplash</a>
                            !
                        </p>
                        <a class="btn btn-dark btn-xl" href="#services">SERVICIOS</a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Services-->
        <section class="content-section bg-primary text-white text-center" id="services">
            <div class="container px-4 px-lg-5">
                <div class="content-section-heading">
                    <h3 class="text-secondary mb-0">Servicios</h3>
                    <h2 class="mb-5">EN DIGITAL - EN FÍSICO</h2>
                </div>
                <div class="row gx-4 gx-lg-5">
                    <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-screen-smartphone"></i></span>
                        <h4><strong>EN TODOS LOS DISPOSITIVOS</strong></h4>
                        <p class="text-faded mb-0">Les damos la oportunidad de tener tu propio Ebook
                            sin haber comprado uno, nosotros les envíamos los libros en formato PDF
                            mediante correo electronico.
                        </p>
                    </div>
                    <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-pencil"></i></span>
                        <h4><strong>ESCRITORES</strong></h4>
                        <p class="text-faded mb-0">Tenemos una sección para nuestros escritores, si les
                            gusta escribir aquí pueden escribir todos sus escritos.</p>
                    </div>
                    <div class="col-lg-3 col-md-6 mb-5 mb-md-0">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-like"></i></span>
                        <h4><strong>FAVORITOS</strong></h4>
                        <p class="text-faded mb-0">
                            Tus libros o escritos favoritos en un apartado de guardados
                            <i class="fas fa-heart"></i>
                            ¡AGREGA!
                        </p>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-mustache"></i></span>
                        <h4><strong>¿DUDAS?</strong></h4>
                        <p class="text-faded mb-0">¿Tienes alguna duda? CONTÁCTANOS</p>
                    </div>
                </div>
            </div>
        </section>
        <!-- Callout-->
        <section class="callout">
            <div class="container px-4 px-lg-5 text-center">
                <h2 class="mx-auto mb-5">
                    BIENVENIDOS A
                    <em>NUESTRA</em>
                    PÁGINA WEB ¡DISFRUTEN!
                </h2>
            </div>
        </section>
        <!-- Call to Action-->
        <section class="content-section bg-primary text-white">
            <div class="container px-4 px-lg-5 text-center">
                <h2 class="mb-4">REGISTRARSE COMO: LECTORES - ESCRITORES
                </h2>
                <a class="btn btn-xl btn-light me-4" href="#!">Escritores</a>
                <a class="btn btn-xl btn-dark" href="#!">Lectores</a>
            </div>
        </section>
        {% endblock %}
        
                

LibrosApp/templates/LibroApp/libros.html
{% extends 'libroApp/padre.html' %}

{%load static%}

{% block contenido1 %}
    <H1>¡Bienvenidos a los libros y escritos!</H1>
    <section>
        {% for elemento in libros %}
        <article>
            <h3>
                {{elemento.nombreLibro}}
            </h3>
            <p>
                {{elemento.descripcion}}
            </p>
            <img src="{{elemento.imagen}}">
            <footer>
                {{elemento.autor}}
            </footer>
            {% if user.id == p.user.id %}
                <div class="btn-group" role="group" aria-label="Basic outlined example">
                    <button type="button" class="btn btn-outline-primary btn-sm"><a href="{% url 'editarLibro' p.titulo %}" style="text-decoration: none;">Editar</a></button>
                    <button type="button" class="btn btn-outline-primary btn-sm"><a href="{% url 'eliminarLibro' p.titulo %}" style="text-decoration: none;">Eliminar</a></button>
                </div>
                {% endif %}
                <div class="btn-group" role="group" aria-label="Basic outlined example">
                <button type="button" class="btn btn-outline-primary btn-sm"><a href="{% url 'detallePost' p.id %}" style="text-decoration: none;">Detalle</a></button>
                </div>
            </article>
        {% endfor %}
    </section>
</body>
</html>
{% endblock %}

LibrosApp/templates/LibroApp/login.html
{% extends 'LibroApp/padre.html' %}

{%load static%}

{% block contenido1 %}

    <form action="" method="post">
        {% csrf_token %}
        {{formulario1.as_p}}
        <button type="submit">Iniciar Sesión</button> 
    </form>


{% endblock %}

LibrosApp/templates/LibroApp/perfil.html
{% extends 'libroApp/padre.html' %}

{%load static%}

{% block contenido1 %}

<div class="main">
    <div class="profile">
        {% if request.user.is_authenticated %}
            {% with first_image=user.avatar_set.first %}
                {% if first_image %}
                    <a href="{{ first_image.imagen.url }}" target="_blank"></a>
                    <img src="{{ first_image.imagen.url }}">
                {% else %}
                    <a href="{% static 'LibroApp/assets/img/blank.png' %}" target="_blank"></a>
                    <img src="{% static 'LibroApp/assets/img/blank.png' %}"/>
                {% endif %}
            {% endwith %}
        {% endif %}
        <h2>{{ user }}</h2>
    </div>
</div>

{% endblock %}

LibrosApp/templates/LibroApp/registro.html
{% extends 'libroApp/padre.html' %}

{%load static%}

{% block contenido1 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>REGISTER</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{formulario2.as_p}}
        <button type="submit">REGISTRAR</button> 
    </form>
</body>
</html>

{% endblock %}

LibrosApp/templates/LibroApp/resultados.html
{% extends 'libroApp/padre.html' %}

{%load static%}

{% block contenido1 %}

<p><h4>{{nombreLibro.titulo}}</h4></p>
{% if nombreLibro.imagen %}
    <p><img class="imagenPost" src="{{nombreLibro.imagen.url}}" alt="No Hay imagen"></p>
{% endif %}
<p>categoría {{nombreLibro.categoría}}</p>
<p>Año: {{nombreLibro.fecha_punlicacion}}</p>
<p>Descrición: {{nombreLibro.descripcion}}</p>
<div class="btn-group" role="group" aria-label="Basic outlined example">
    <button type="button" class="btn btn-outline-primary btn-sm"><a href="{% url 'Posteos' %}" style="color: rgb(162, 213, 255); text-decoration: none;">Regresar</a></button>
</div>


{% endblock %}